# name: CI
# 
# on: [push]
# 
# jobs:
#   build:
# 
#     runs-on: ubuntu-latest
#     
#     steps:
#     - uses: actions/checkout@v1
#     - name: Run a one-line script
#       run: echo Hello, world!
#     - name: Run a multi-line script
#       run: |
#         echo Add other actions to build,
#         echo test, and deploy your project.

name: Build Check
on: push
jobs:
    build:
        name: test build
        runs-on: windows-latest
        strategy:
            fail-fast: false
            matrix:
                visualstudio: ["Visual Studio 16 2019"]
                #, "Visual Studio 15 2017"]
                architecture:
                    - x64
                    - x86
                config:
                    - Debug
                    - Release
                include:
                    - architecture: x64
                      platform: x64
                      triplet: x64-windows
                    - architecture: x86
                      platform: Win32
                      triplet: x86-windows
        steps:
            - uses: actions/checkout@v2
            # https://github.com/marketplace/actions/setup-python-environment
            - uses: actions/setup-python@v1
              with:
                  python-version: '3.x'
            - name: Cache Vcpkg modules
              uses: actions/cache@v1
              with:
                path: c:\vcpkg\installed # npm cache files are stored in `~/.npm` on Linux/macOS
                key: ${{ runner.os }}-vcpkg-${{ matrix.triplet }}
                # restore-keys: |
                #   ${{ runner.os }}-node-${{ env.cache-name }}-
                #   ${{ runner.os }}-node-
                #   ${{ runner.os }}-
            - run: |
                cmake --version
                cmake --help
                python --version
              shell: cmd
            # - run: git --version
#            - run: python show.py "${{ matrix.visualstudio }}"
#              shell: bash
            - run: |
                cd
                set
              shell: cmd
            # - run: vcpkg list
#            - name: Install ${{ matrix.architecture }} ${{ matrix.config }}
#              run: |
#                  python build_github_actions.py install "${{ matrix.visualstudio }}" ${{ matrix.architecture }} ${{ matrix.config }}
#                  type install.bat
#                  install.bat
#              shell: cmd
            - name: Install Vcpkg packages (${{ matrix.architecture }})
              run: vcpkg install --triplet ${{ matrix.triplet }} glew glfw3 glm
              shell: cmd
            - name: Show Vcpkg tool chain file
              run: dir C:\vcpkg\scripts\buildsystems
              shell: cmd

#            - name: Build ${{ matrix.architecture }} ${{ matrix.config }}
#              run: |
#                  python build_github_actions.py build "${{ matrix.visualstudio }}" ${{ matrix.architecture }} ${{ matrix.config }} ${{ matrix.platform }}
#                  type build.bat
#                  build.bat
#                  # cd %GITHUB_WORKSPACE%
#                  # if not exist "build${{ matrix.visualstudio }}" mkdir "build${{ matrix.visualstudio }}"
#                  # cd "build${{ matrix.visualstudio }}"
#                  # cmake -G"${{ matrix.visualstudio }}" ..
#                  # cmake --build . --config ${{ matrix.config }}
#              shell: cmd
            - name: Build project (${{ matrix.architecture }}, ${{ matrix.config }})
              run: |
                mkdir build
                cd build
                cmake -A ${{ matrix.platform }} -G"${{ matrix.visualstudio }}" -DCMAKE_TOOLCHAIN_FILE=%VCPKG_INSTALLATION_ROOT%\scripts\buildsystems\vcpkg.cmake -DVCPKG_TARGET_TRIPLET=${{ matrix.triplet }} ..
                cmake --build . --config ${{ matrix.config }}
                cd ..
              shell: cmd
