name: Build Check
on: push
jobs:
    build:
        name: test build
        runs-on: windows-latest
        env:
          VCPKG_PACKAGES: glew glfw3 glm
        strategy:
            fail-fast: false
            matrix:
                visualstudio: ["Visual Studio 16 2019"]
                architecture:
                    - x64
                    - x86
                config:
                    - Debug
                    - Release
                include:
                    - architecture: x64
                      platform: x64
                      triplet: x64-windows
                    - architecture: x86
                      platform: Win32
                      triplet: x86-windows
        steps:
            - uses: actions/checkout@v2
            # https://github.com/marketplace/actions/setup-python-environment
            - uses: actions/setup-python@v1
              with:
                  python-version: '3.x'
            - name: Cache Vcpkg modules
              id: cache-vcpkg
              uses: actions/cache@v1
              with:
                path: '%VCPKG_INSTALLATION_ROOT%\installed' # npm cache files are stored in `~/.npm` on Linux/macOS
                key: ${{ runner.os }}-${{ matrix.visualstudio }}-vcpkg-${{ matrix.triplet }}-${{ env.VCPKG_PACKAGES }}
                restore-keys: |
                  ${{ runner.os }}-${{ matrix.visualstudio }}-vcpkg-${{ matrix.triplet }}-
                  ${{ runner.os }}-${{ matrix.visualstudio }}-vcpkg-
                #   ${{ runner.os }}-node-${{ env.cache-name }}-
                #   ${{ runner.os }}-node-
                #   ${{ runner.os }}-
            - run: |
                cmake --version
                cmake --help
                python --version
              shell: cmd
            - run: |
                cd
                set
              shell: cmd
            - name: Install Vcpkg packages (${{ matrix.architecture }})
              if: steps.cache-vcpkg.outputs.cache-hit != 'true'
              run: vcpkg install --triplet ${{ matrix.triplet }} glew glfw3 glm
              shell: cmd
            - name: Show Vcpkg tool chain file
              run: dir C:\vcpkg\scripts\buildsystems
              shell: cmd
            - name: Build project (${{ matrix.architecture }}, ${{ matrix.config }})
              run: |
                mkdir build
                cd build
                cmake -A ${{ matrix.platform }} -G"${{ matrix.visualstudio }}" -DCMAKE_TOOLCHAIN_FILE=%VCPKG_INSTALLATION_ROOT%\scripts\buildsystems\vcpkg.cmake -DVCPKG_TARGET_TRIPLET=${{ matrix.triplet }} ..
                cmake --build . --config ${{ matrix.config }}
                cd ..
              shell: cmd
